# Minimal bottom prompt configuration
format = "$character"

# No right prompt
right_format = ""

# Simple arrow character
[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

# Command duration with minimal styling
[cmd_duration]
format = "[$duration](dimmed)"
min_time = 0

# Time format
[time]
disabled = false
time_format = "%H:%M"
format = "[$time](dimmed)"