alias ls='ls -G'
alias ll='ls -lG'
alias vim='nvim'
alias kot='cat'
alias be='bundle exec'

alias gs='git status'
alias ga='git add'
alias gp='git push'
alias gc='git commit'
alias gb='git branch'
alias gCm='git checkout master'
alias gCnb='git checkout -b'
alias gCb='git checkout'

